import { useState } from "react";
import { api } from "../api/client.js";
import { CodeIcon } from "./icons.jsx";

export default function CodeGenerator({ taskText }) {
  const [state, setState] = useState("idle"); // idle | loading | done | error
  const [code, setCode] = useState("");
  const [error, setError] = useState("");

  const handleGenerate = async () => {
    setState("loading");
    setError("");
    try {
      const { code } = await api.generateScript(taskText);
      setCode(code);
      setState("done");
    } catch (err) {
      setError(err.message);
      setState("error");
    }
  };

  if (state === "loading") {
    return (
      <button className="generate-code-btn" disabled>
        <span className="spinner" /> Generating&hellip;
      </button>
    );
  }

  if (state === "error") {
    return (
      <div className="generate-code-error">
        <p className="error small">{error}</p>
        <button className="generate-code-btn" onClick={handleGenerate}>
          <CodeIcon size={15} /> Try again
        </button>
      </div>
    );
  }

  if (state === "done") {
    return (
      <div className="generated-code-block">
        <div className="generated-code-header">
          <span className="muted small">Generated by Gemini from the matched pattern above</span>
          <button className="link-button" onClick={handleGenerate}>
            Regenerate
          </button>
        </div>
        <pre>
          <code>{code}</code>
        </pre>
      </div>
    );
  }

  return (
    <button className="generate-code-btn" onClick={handleGenerate}>
      <CodeIcon size={15} /> Generate code
    </button>
  );
}
